### ISSUE TITLE
安装ppmpeg之后报错

### ISSUE THREAD

**Issue by Black-J-Code** [jiji262/xiaoetong-video-downloader#1]
Traceback (most recent call last):
  File "D:\Python\Python37\lib\site-packages\ffmpy.py", line 95, in run
    stderr=stderr
  File "D:\Python\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "D:\Python\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by Black-J-Code** [comment]
ffmpeg、ffmpy、都安装了

**Comment by jiji262** [comment]
Windows上没有测试，我在Mac上没有问题。
