### ISSUE TITLE
登陆扫码之后没有反应

### ISSUE THREAD

**Issue by pericn** [jiji262/xiaoetong-video-downloader#11]
强行终止提示
`
Traceback (most recent call last):
  File "xiaoet.py", line 272, in <module>
    main()
  File "xiaoet.py", line 259, in main
    xet = Xet(args.appid, args.login)
  File "xiaoet.py", line 20, in __init__
    self.session = self.login(re_login)
  File "xiaoet.py", line 67, in login
    time.sleep(1)
KeyboardInterrupt
`

**Comment by atheneus** [comment]
一样的问题，扫了qrcode文件，重新执行命令还是提示登录被拒，加了sudo执行，没有反应，无文字输出，只能强行终止

**Comment by lms1206** [comment]
多扫两次

**Comment by pericn** [comment]
> 多扫两次

？扫了很多次哈。都没用。

**Comment by lms1206** [comment]
> > 多扫两次
> 
> ？扫了很多次哈。都没用。

抱歉 没能复现问题

**Comment by pericn** [comment]
> > > 多扫两次
> > 
> > 
> > ？扫了很多次哈。都没用。
> 
> 抱歉 没能复现问题

今天终于解决了问题。原因是在移动端复制的链接，所有字母都自动小写，需要在桌面端打开链接，找到带大写字母的店铺 id。

**Comment by along979** [comment]
感谢，原来是因为大小写的问题，已成功下载。
