### ISSUE TITLE
运行报错 不知何故

### ISSUE THREAD

**Issue by kof0012** [jiji262/xiaoetong-video-downloader#3]
你好，我下载文件的时候，提示错误，不理解是什么原因导致无法下载。能否帮忙看看。谢谢。

```
Traceback (most recent call last):
  File ".\xiaoet.py", line 272, in <module>
    main()
  File ".\xiaoet.py", line 261, in main
    xet.download(args.d, args.nocache)
  File ".\xiaoet.py", line 227, in download
    resource_list = [self.get_resource(resource['id']) for resource in self.get_resource_list(id)]
  File ".\xiaoet.py", line 227, in <listcomp>
    resource_list = [self.get_resource(resource['id']) for resource in self.get_resource_list(id)]
  File ".\xiaoet.py", line 142, in get_resource
    content = ast.literal_eval(res.content.decode("UTF-8"))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\ast.py", line 91, in literal_eval
    return _convert(node_or_string)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\ast.py", line 79, in _convert
    map(_convert, node.values)))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\ast.py", line 90, in _convert
    return _convert_signed_num(node)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\ast.py", line 63, in _convert_signed_num
    return _convert_num(node)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\ast.py", line 55, in _convert_num
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.Name object at 0x000001794CB9D978>
```

**Comment by kof0012** [comment]
PS D:\xet> python .\xiaoet.py applAath11j8192 -d p_5d5669a41e4ad_tOIHGBfD

**Comment by jiji262** [comment]
本程序在Mac测试使用正常，Windows上没有测过，不知道会不会有什么问题，见谅。

**Comment by youmenputao** [comment]
我运行是出来这个报错
C:\Users\Xinchen\AppData\Local\Programs\Python\Python38-32\python.exe D:/Python/xet/xiaoet.py applAath11j8192 -d p_5d5669a41e4ad_tOIHGBfD
name: 微信大号投稿渠道 resourceid: p_5d5675d22a733_SwUniGL6
name: 写作地图2.0视频讲解 resourceid: p_5d566794eb46b_Ie0wePy0
name: 新媒体写作八节课 resourceid: p_5d0c791a9bd9f_qjGb2eY6
Traceback (most recent call last):
  File "D:/Python/xet/xiaoet.py", line 272, in <module>
    main()
  File "D:/Python/xet/xiaoet.py", line 261, in main
    xet.download(args.d, args.nocache)
  File "D:/Python/xet/xiaoet.py", line 227, in download
    resource_list = [self.get_resource(resource['id']) for resource in self.get_resource_list(id)]
  File "D:/Python/xet/xiaoet.py", line 227, in <listcomp>
    resource_list = [self.get_resource(resource['id']) for resource in self.get_resource_list(id)]
  File "D:/Python/xet/xiaoet.py", line 142, in get_resource
    content = ast.literal_eval(res.content.decode("UTF-8"))
  File "C:\Users\Xinchen\AppData\Local\Programs\Python\Python38-32\lib\ast.py", line 99, in literal_eval
    return _convert(node_or_string)
  File "C:\Users\Xinchen\AppData\Local\Programs\Python\Python38-32\lib\ast.py", line 88, in _convert
    return dict(zip(map(_convert, node.keys),
  File "C:\Users\Xinchen\AppData\Local\Programs\Python\Python38-32\lib\ast.py", line 98, in _convert
    return _convert_signed_num(node)
  File "C:\Users\Xinchen\AppData\Local\Programs\Python\Python38-32\lib\ast.py", line 75, in _convert_signed_num
    return _convert_num(node)
  File "C:\Users\Xinchen\AppData\Local\Programs\Python\Python38-32\lib\ast.py", line 66, in _convert_num
    _raise_malformed_node(node)
  File "C:\Users\Xinchen\AppData\Local\Programs\Python\Python38-32\lib\ast.py", line 63, in _raise_malformed_node
    raise ValueError(f'malformed node or string: {node!r}')
ValueError: malformed node or string: <_ast.Name object at 0x036E7E20>

进程已结束，退出代码 1

**Comment by hufhqoiqjdjojdqjd-xx** [comment]
![macOS 10.14-2020-07-17-17-41-01.png](https://i.loli.net/2020/07/17/FNbjwvJV7xBnfMp.png)
mac复现结果
